# Generated by Django 3.2.9 on 2021-12-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='description',
        ),
    ]
