# Generated by Django 3.2.9 on 2021-12-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211204_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='creator',
            field=models.CharField(default='Admin', max_length=200),
        ),
    ]
